# Generated by Django 4.1.1 on 2022-09-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('scan_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_region_id', models.IntegerField(unique=True)),
                ('region', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, unique=True)),
                ('query_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hh.queries')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hh.skills')),
            ],
        ),
        migrations.AddField(
            model_name='queries',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hh.regions'),
        ),
    ]
